name: spiral-cavitation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - ipywidgets
  - jupyterlab
  - notebook
  - openpyxl
  - seaborn
  - pip
  - pip:
      - tqdm
